<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Neeru" failures="1" tests="10" name="giveAward.giveAward_flow" time="156.271" errors="1" timestamp="2024-03-29T10:56:06 IST" skipped="0">
  <testcase classname="giveAward.giveAward_flow" name="GiveAwardFlowSingle" time="36.149"/>
  <system-out/>
  <testcase classname="giveAward.giveAward_flow" name="GiveAward_single_Amount_Deduction_Admin" time="14.486"/>
  <system-out>
    <![CDATA[1.0Point is deducted]]>
  </system-out>
  <testcase classname="giveAward.giveAward_flow" name="SocialFeedIDGet" time="4.852"/>
  <system-out/>
  <testcase classname="giveAward.giveAward_flow" name="LikePositive" time="9.523"/>
  <system-out/>
  <testcase classname="giveAward.giveAward_flow" name="CommentPositiveNegative" time="8.767">
    <error message="element click intercepted: Element &lt;img class=&quot;closeCommentBox&quot; onclick=&quot;closeCommentOverlay(4769416);&quot; src=&quot;https://cdn2.workadvantage.in/images/img/image/271568/c5a0b4213a.png&quot; alt=&quot;cross&quot; style=&quot;width: 12px; visibility: visible;&quot;&gt; is not clickable at point (3653, 919). Other element would receive the click: &lt;div class=&quot;loading-indicator-benefit&quot; style=&quot;z-index: 100000;&quot;&gt;&lt;/div&gt;
  (Session info: MicrosoftEdge=122.0.2365.92)
Build info: version: &#039;4.8.2&#039;, revision: &#039;826dbfc730&#039;
System info: os.name: &#039;Windows 11&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;10.0&#039;, java.version: &#039;17.0.10&#039;
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [7a3476f9a9a54b30974151fcd6efbe55, clickElement {id=f.58C74E5BBA4391433FBA0A8D4238C72C.d.3C69DC7282D8F2BCBAA5D04CC71F905B.e.1813}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 122.0.2365.92, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:56135}, msedge: {msedgedriverVersion: 122.0.2365.113 (9bf34bfff1f..., userDataDir: C:\Users\AC\AppData\Local\T...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:56135/devtoo..., se:cdpVersion: 122.0.2365.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on WINDOWS (7a3476f9a9a54b30974151fcd6efbe55)] -&gt; xpath: //div[@id=&#039;newsfeed-4769416&#039;]//img[@class=&#039;closeCommentBox&#039;]]
Session ID: 7a3476f9a9a54b30974151fcd6efbe55" type="org.openqa.selenium.ElementClickInterceptedException">
      <![CDATA[org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <img class="closeCommentBox" onclick="closeCommentOverlay(4769416);" src="https://cdn2.workadvantage.in/images/img/image/271568/c5a0b4213a.png" alt="cross" style="width: 12px; visibility: visible;"> is not clickable at point (3653, 919). Other element would receive the click: <div class="loading-indicator-benefit" style="z-index: 100000;"></div>
  (Session info: MicrosoftEdge=122.0.2365.92)
Build info: version: '4.8.2', revision: '826dbfc730'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.edge.EdgeDriver
Command: [7a3476f9a9a54b30974151fcd6efbe55, clickElement {id=f.58C74E5BBA4391433FBA0A8D4238C72C.d.3C69DC7282D8F2BCBAA5D04CC71F905B.e.1813}]
Capabilities {acceptInsecureCerts: false, browserName: MicrosoftEdge, browserVersion: 122.0.2365.92, fedcm:accounts: true, ms:edgeOptions: {debuggerAddress: localhost:56135}, msedge: {msedgedriverVersion: 122.0.2365.113 (9bf34bfff1f..., userDataDir: C:\Users\AC\AppData\Local\T...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: WINDOWS, proxy: Proxy(), se:cdp: ws://localhost:56135/devtoo..., se:cdpVersion: 122.0.2365.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Element: [[EdgeDriver: MicrosoftEdge on WINDOWS (7a3476f9a9a54b30974151fcd6efbe55)] -> xpath: //div[@id='newsfeed-4769416']//img[@class='closeCommentBox']]
Session ID: 7a3476f9a9a54b30974151fcd6efbe55
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:193)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:183)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:257)
at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:78)
at giveAward.giveAward_flow.CommentPositiveNegative(giveAward_flow.java:349)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- CommentPositiveNegative -->
  <system-out/>
  <testcase classname="giveAward.giveAward_flow" name="Appriate_emp_mail_Negative" time="22.637"/>
  <system-out/>
  <testcase classname="giveAward.giveAward_flow" name="Give_award_custom_msg_negative" time="15.856"/>
  <system-out/>
  <testcase classname="giveAward.giveAward_flow" name="Give_award_value_Statement_positive" time="18.249">
    <failure message="The following asserts failed:
	Assertion failed for value statement expected [Trst] but found [Trust]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Assertion failed for value statement expected [Trst] but found [Trust]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at giveAward.giveAward_flow.Give_award_value_Statement_positive(giveAward_flow.java:625)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Give_award_value_Statement_positive -->
  <system-out/>
  <testcase classname="giveAward.giveAward_flow" name="GiveAward_Point_Transfer_negative_Single" time="17.227"/>
  <system-out/>
  <testcase classname="giveAward.giveAward_flow" name="Appriated_List_Test" time="8.525"/>
  <system-out/>
</testsuite> <!-- giveAward.giveAward_flow -->
